"""add trip destination/notes and travel_event

Revision ID: a1f42c9d8b3e
Revises: 9e79a029a750
Create Date: 2026-08-22 09:00:00.000000

Module 02 (Travel Schedule), built directly from `Module_02_Travel_Schedule_Spec.md` rather than
a ratified `spec.md` — see the owner's explicit instruction recorded in this iteration's history
to bypass the speckit workflow for this module.

Hand-written rather than autogenerated, following the same rule the two prior migrations that add
an enum column both name: `create_type=False` on the enum column, with the type created and
dropped explicitly here, so a second `upgrade` after a `downgrade` does not fail with "type
traveleventtype already exists".

`trip.destination` and `trip.notes` are both nullable additions to the existing 003 table — an
existing Trip row reads back with both null, not broken.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "a1f42c9d8b3e"
down_revision: str | None = "9e79a029a750"
branch_labels: str | None = None
depends_on: str | None = None

# create_type=False so the type is created and dropped only where this file says so.
travel_event_type_enum = postgresql.ENUM(
    "transport", "stay", "activity", "food", "note", name="traveleventtype", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    travel_event_type_enum.create(bind, checkfirst=False)

    op.add_column("trip", sa.Column("destination", sa.String(length=200), nullable=True))
    op.add_column("trip", sa.Column("notes", sa.Text(), nullable=True))

    op.create_table(
        "travel_event",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("event_type", travel_event_type_enum, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("from_location", sa.String(length=120), nullable=True),
        sa.Column("to_location", sa.String(length=120), nullable=True),
        sa.Column("booking_reference", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_travel_event_trip_id"), "travel_event", ["trip_id"], unique=False)
    op.create_index(op.f("ix_travel_event_event_type"), "travel_event", ["event_type"], unique=False)
    op.create_index(op.f("ix_travel_event_event_date"), "travel_event", ["event_date"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_travel_event_event_date"), table_name="travel_event")
    op.drop_index(op.f("ix_travel_event_event_type"), table_name="travel_event")
    op.drop_index(op.f("ix_travel_event_trip_id"), table_name="travel_event")
    op.drop_table("travel_event")

    op.drop_column("trip", "notes")
    op.drop_column("trip", "destination")

    bind = op.get_bind()
    travel_event_type_enum.drop(bind, checkfirst=False)
